Update pakcagejson
Lat3xKitty/lovense-forza pull request #2
Opened 2022-06-17 14:22 UTC by TrappyChastity

Noticed too late to add it in the other PR

2022-06-17 14:47 UTC, Lat3xKitty requested changes
Loving the changes, there's the few comments regarding how the Vibration works which just wanna clear up and fix before adding it 😊

2022-06-17 14:47 UTC, Lat3xKitty commented on index.js
> +    let vibration = 0.1;
I deliberately had this set at 0, so it would disable vibrations while in the menu and stuff like that.
🤔 Any reason for setting this to 0.1?

2022-06-17 14:47 UTC, Lat3xKitty commented on index.js
> +      sendVibration(vibrationInt);
This goes again with the 0.1, as this won't "reset" the toy when you enter menus and stuff like that and keep it running on the last power it had known.

2022-06-17 14:47 UTC, Lat3xKitty commented on index.js
> +      forza.on('telemetry', throttle(processData, 100));
This is currently "out of bounds" and never actually starts the event running 😂
Guessing this was a slight miss placement of the event handler.

2022-06-17 14:48 UTC, Lat3xKitty commented on index.js
> +      sendVibration(vibrationInt);
Just needs to be set outside of the `isRaceOn`

2022-06-17 14:58 UTC, Lat3xKitty commented
**TODO** 

_- `domain` is just the local ip address of the computer the app is running on with `.lovense.club` on the ends, this can be gotten automatically_
_- `port` will always be `30010` (unless something is already using that, so there should be a check for that  otherwise just use for that  otherwise just use the default and don't bother asking)_

**Yes I agree both of these should be automatic, but as originally mentioned, this was a quick 30 minute push to make it, and was a thing I was going to do in some more freetime.**

_- `toyID` Should be able to be grabbed automatically by querying the [getToys](https://api.lovense.com/api/lan/getToys) and looking for the one that is active_
_-   Either taking the first found or if there are more than one, perhaps offering a selection using the device `name`, `type`, `nickname` and `hVersion`) for the user to select_
 
  **Probably should do something to select which toy(s) they would like to control on start up from the getToys list, probably only worth really implementing vibrate for now as I don't think that the Pump/Rotate are too ideal for an implementation like this.
  My idea was:**
  ```
   [1] Domi (Vibe) - Battery (100%)
   [2] Hush (Plug) - Battery (65%) 
   
   Please select which toy(s) you would like to use, separating each one with a comma or space:  (I.E. 1,2)
   >
   ```

  - The vibration modes should not need to be manually entered into the JavaScript. passing them as command line params would be a huge improvement
  - Same with the `maxVibration`
  
  **This should probably be something similar to the toy thing above, but likely add a .env file to remember what the user has last selected if they enter blank in either of these sections, and possibly add a `--use-config` parameter to always skip the questions :)**

2022-06-24 11:35 UTC, merged

2022-06-24 14:41 UTC, TrappyChastity commented on index.js
> +    let vibration = 0.1;
i for get the reason, i think it was something about just highlighting how to specify the var. or there was some thing that wasn't working when it was o,  or something else

2022-06-24 14:44 UTC, TrappyChastity commented on index.js
> +      forza.on('telemetry', throttle(processData, 100));
yeah, i got confused with this one for a bit, i did fix it but was merged already after you had done so. so nvm